import {
  faCoffee,
  faHeart,
  faHandshake,
  faUser,
  faSeedling,
  faAngleRight,
  faAngleLeft,
  faBars,
  faXmark,
  faPaperPlane,
  faHandHoldingHeart,
  faArrowDown,
  faGraduationCap,
  faHandsHelping,
  faDonate,
  faUsers,
  faCheck,
  faQuoteLeft,
  faArrowRight,
  faLeaf,
  faLock,
  faShield,
  faArrowUp,
  faHeartbeat,
  faVenus,
  faUserGraduate,
  faTree,
  faHome,
  faBookOpen,
  faCheckCircle,
  faExclamationCircle,
  faMapMarkedAlt,
  faMapMarkerAlt,
  faPhoneAlt,
  faEnvelope,
  faClock,
  faBriefcase,
  faLaptopCode,
  faRocket,
  faGlobe,
  faMedal,
  faLaptop,
  faCode,
  faLanguage,
  faLightbulb,
  faRobot,
  faChartLine,
  faUserPlus,
  faChalkboardTeacher,
  faUserTie,
  faBook,
  faClipboardList,
  faBullseye,
  faChartBar,
  faMousePointer,
  faScaleBalanced,
  faPeopleGroup,
  faHandsHoldingChild,
  faChildReaching,
  faDesktop,
  faUniversalAccess,
  faPeopleCarry,
  faHandHoldingDollar,
  faLaptopFile,
  faShapes,
  faFilePen,
  faUserGear,
} from "@fortawesome/free-solid-svg-icons";
import {
  faFacebook,
  faTwitter,
  faInstagram,
  faLinkedin,
  faGithub,
} from "@fortawesome/free-brands-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
export const iconMap = {
  coffee: faCoffee,
  heart: faHeart,
  handshake: faHandshake,
  user: faUser,
  seedling: faSeedling,
  rightMove: faAngleRight,
  leftMove: faAngleLeft,
  bar: faBars,
  xmark: faXmark,
  twitter: faTwitter,
  facebook: faFacebook,
  instagram: faInstagram,
  linkedin: faLinkedin,
  github: faGithub,
  paperplane: faPaperPlane,
  HeartInHand: faHandHoldingHeart,
  arrowdown: faArrowDown,
  graduationCap: faGraduationCap,
  handsHelping: faHandsHelping,
  donate: faDonate,
  users: faUsers,
  check: faCheck,
  quoteLeft: faQuoteLeft,
  arrowRight: faArrowRight,
  leaf: faLeaf,
  lock: faLock,
  sheild: faShield,
  arrowup: faArrowUp,
  heartbeat: faHeartbeat,
  venus: faVenus,
  userGraduate: faUserGraduate,
  tree: faTree,
  home: faHome,
  bookOpen: faBookOpen,
  checkCircle: faCheckCircle,
  exclamationCircle: faExclamationCircle,
  mapMarkerAlt: faMapMarkerAlt,
  phoneAlt: faPhoneAlt,
  envelope: faEnvelope,
  clock: faClock,
  briefcase: faBriefcase,
  laptopCode: faLaptopCode,
  rocket: faRocket,
  globe: faGlobe,
  medal: faMedal,
  laptop: faLaptop,
  code: faCode,
  language: faLanguage,
  lightbulb: faLightbulb,
  robot: faRobot,
  userGraduate: faUserGraduate,
  tree: faTree,
  home: faHome,
  bookOpen: faBookOpen,
  checkCircle: faCheckCircle,
  exclamationCircle: faExclamationCircle,
  mapMarkerAlt: faMapMarkerAlt,
  phoneAlt: faPhoneAlt,
  envelope: faEnvelope,
  clock: faClock,
  chartLine: faChartLine,
  userPlus: faUserPlus,
  chalkboardTeacher: faChalkboardTeacher,
  userTie: faUserTie,
  book: faBook,
  clipboardList: faClipboardList,
  bullseye: faBullseye,
  chartBar: faChartBar,
  mousePointer: faMousePointer,
  scaleBased: faScaleBalanced,
  peopleGroup: faPeopleGroup,
  handHoldingChild: faHandsHoldingChild,
  childReaching: faChildReaching,
  desktop: faDesktop,
  universalAccess: faUniversalAccess,
  peopleCarry:faPeopleCarry,
  handHoldingDollar:faHandHoldingDollar,
  laptopFile:faLaptopFile,
  shapes:faShapes,
  filePen:faFilePen,
  useGear:faUserGear,
};
